# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  workflow_dispatch:
#   pull_request:
#     branches: [ main ]
    




jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./team-fingerprints-api
    environment: team-fingerprint
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        env:
          AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
          AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
          AUTH0_DOMAIN: ${{secrets.AUTH0_DOMAIN}}
          AUTH0_ISSUER: ${{secrets.AUTH0_ISSUER}}
          AUTH0_MANAGEMENT_API_TOKEN: ${{secrets.AUTH0_MANAGEMENT_API_TOKEN}}
          ENV: ${{secrets.ENV}}
          MONGODB_URI: ${{secrets.MONGODB_URI}}

      - run: npm i
      - run: npm run build
      - name: 'Test envs'
        run: echo ${{ env }}
      - run: npm run test:e2e
    

